name: 'Jenkins Triggerer'
description: 'Trigger Jenkins jobs with ease! Derived from build-jenkins-job action.'

inputs:
  JENKINS_URL:
    description: 'Jenkins server url'
    required: true
  JENKINS_USERNAME:
    description: 'Jenkins username'
    required: true
  JENKINS_API_TOKEN:
    description: 'Jenkins user API token. Can be generated via <jenkins-server>/user/<username>/configure'
    required: true
  JENKINS_JOB:
    description: 'Jenkins job to trigger'
    required: true
  JENKINS_JOB_PARAMETERS:
    description: "Job parameters in JSON string format, i.e '{'param1': 'value1', 'param2': 'value2'}' "
    required: false

outputs:
  job_status:
    description: 'Build status'

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.JENKINS_URL }}
    - ${{ inputs.JENKINS_USERNAME }}
    - ${{ inputs.JENKINS_API_TOKEN }}
    - ${{ inputs.JENKINS_JOB }}
    - ${{ inputs.JENKINS_JOB_PARAMETERS }}